package com.example.nework.dao

import androidx.paging.PagingSource
import androidx.room.Dao
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import com.example.nework.entity.PostEntity

@Dao
interface PostDao {
    @Query("SELECT * FROM PostEntity ORDER BY id DESC")
    fun pagingSource(): PagingSource<Int, PostEntity>
    //pagingsource autogenerated by room
    //manual create pagingSource NOT! recommended

    @Query("SELECT * FROM PostEntity WHERE id = :id")
    fun getPostById(id: Int): PostEntity

    @Query("SELECT COUNT(*) FROM PostEntity")
    fun getSize(): Int

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insert(post: PostEntity)

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insert(posts: List<PostEntity>)

    @Query("DELETE FROM PostEntity WHERE id = :id")
    suspend fun removeById(id: Int)

    @Query(
        """
                UPDATE PostEntity SET
                    likes = likes + CASE WHEN likedByMe THEN -1 ELSE 1 END,
                    likedByMe = CASE WHEN likedByMe THEN 0 ELSE 1 END
                WHERE id = :id;
            """
    )
    suspend fun likePostById(id: Int)

    @Query(
        """
                UPDATE PostEntity SET
                    isLikeLoading = CASE WHEN isLikeLoading THEN 0 ELSE 1 END
                WHERE id = :id;
            """
    )
    suspend fun changeLikeLoadingById(id: Int)

    //for paging
    @Query("SELECT COUNT(*) == 0 FROM PostEntity")
    suspend fun isEmpty(): Boolean

    //for paging
    @Query("SELECT max(id) FROM PostEntity")
    suspend fun max():Int?

    //for paging
    @Query("SELECT min(id) FROM PostEntity")
    suspend fun min():Int?
}
//RECYCLE BIN
/*
    //useless with paging
    @Query("SELECT * FROM PostEntity ORDER BY id DESC")
    @Query(
        """
            SELECT * FROM PostEntity
            ORDER BY
            CASE id WHEN id < 0 THEN 1 ELSE 0 END DESC,
            ABS(id) DESC
            """
    )
    fun getAll(): Flow<List<PostEntity>>

    //useless without drafts
    @Query("SELECT id FROM PostEntity WHERE id = :id")
    fun isIdExists(id: Long): Int //0 or 1 selected items

    //insert(post) have save script
    @Upsert
    suspend fun save(post: PostEntity): Int

    //like-fun will get loading animation with api-answer later
    @Query(
        """
                UPDATE PostEntity SET
                    likes = likes + CASE WHEN likedByMe THEN -1 ELSE 1 END,
                    likedByMe = CASE WHEN likedByMe THEN 0 ELSE 1 END
                WHERE id = :id;
            """
    )
    suspend fun likeById(id: Long)

    @Query("SELECT max(id) FROM PostEntity")
    suspend fun max():Int?

    @Query("SELECT min(id) FROM PostEntity")
    suspend fun min():Int?

    @Query("SELECT id FROM PostEntity WHERE id = :id")
    fun isIdExists(id: Int): Int //0 or 1 selected items
*/